# Generated by Django 5.2 on 2025-04-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyParce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Utilities'), ('HEALTH', 'Health'), ('ALL', 'All')], default='All', max_length=50),
        ),
    ]
