# Generated by Django 5.2 on 2025-04-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyParce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BANK FEES', 'Bank Fees'), ('COMMUNITY', 'Community'), ('FOOD AND DRINK', 'Food and Drink'), ('HEALTHCARE', 'Healthcare'), ('INTEREST', 'Interest'), ('PAYMENT', 'Payment'), ('RECREATION', 'Recreation'), ('SERVICE', 'Service'), ('SHOPS', 'Shops'), ('TRANSFER', 'Transfer'), ('TRAVEL', 'Travel'), ('ALL', 'All')], default='All', max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('BANK FEES', 'Bank Fees'), ('COMMUNITY', 'Community'), ('FOOD AND DRINK', 'Food and Drink'), ('HEALTHCARE', 'Healthcare'), ('INTEREST', 'Interest'), ('PAYMENT', 'Payment'), ('RECREATION', 'Recreation'), ('SERVICE', 'Service'), ('SHOPS', 'Shops'), ('TRANSFER', 'Transfer'), ('TRAVEL', 'Travel')], default='Other', max_length=50),
        ),
    ]
